type CurrencyCode = string;
type Rates = number;

interface CurrencyRate {
  selling: number;
  buyingTT: number;
  buyingDD: number;
}

interface ProcessedData {
  date: string;
  base: string;
  rates: Record<CurrencyCode, CurrencyRate>;
}

interface MidMarketData {
  date: string;
  base: string;
  rates: Record<CurrencyCode, Rates>;
}

interface ExchangeRateData {
  holiday: number;
  id: number;
  CreateDate: string | null;
  RateDate: string;
  RateYear: number | null;
  RateMonth: number | null;
  RateDay: number | null;
  AUDSelling: string | null;
  AUDBuyingTT: string | null;
  AUDBuyingOD: string | null;
  ATSSelling: string | null;
  ATSBuyingTT: string | null;
  ATSBuyingOD: string | null;
  BEFSelling: string | null;
  BEFBuyingTT: string | null;
  BEFBuyingOD: string | null;
  BNDSelling: string | null;
  BNDBuyingTT: string | null;
  BNDBuyingOD: string | null;
  CADSelling: string | null;
  CADBuyingTT: string | null;
  CADBuyingOD: string | null;
  DKKSelling: string | null;
  DKKBuyingTT: string | null;
  DKKBuyingOD: string | null;
  DEMSelling: string | null;
  DEMBuyingTT: string | null;
  DEMBuyingOD: string | null;
  NLGSelling: string | null;
  NLGBuyingTT: string | null;
  NLGBuyingOD: string | null;
  FRFSelling: string | null;
  FRFBuyingTT: string | null;
  FRFBuyingOD: string | null;
  INRSelling: string | null;
  INRBuyingTT: string | null;
  INRBuyingOD: string | null;
  ITLSelling: string | null;
  ITLBuyingTT: string | null;
  ITLBuyingOD: string | null;
  JPYSelling: string | null;
  JPYBuyingTT: string | null;
  JPYBuyingOD: string | null;
  MYRSelling: string | null;
  MYRBuyingTT: string | null;
  MYRBuyingOD: string | null;
  NZDSelling: string | null;
  NZDBuyingTT: string | null;
  NZDBuyingOD: string | null;
  NOKSelling: string | null;
  NOKBuyingTT: string | null;
  NOKBuyingOD: string | null;
  PKRSelling: string | null;
  PKRBuyingTT: string | null;
  PKRBuyingOD: string | null;
  PHPSelling: string | null;
  PHPBuyingTT: string | null;
  PHPBuyingOD: string | null;
  PTESelling: string | null;
  PTEBuyingTT: string | null;
  PTEBuyingOD: string | null;
  SGDSelling: string | null;
  SGDBuyingTT: string | null;
  SGDBuyingOD: string | null;
  ZARSelling: string | null;
  ZARBuyingTT: string | null;
  ZARBuyingOD: string | null;
  ESPSelling: string | null;
  ESPBuyingTT: string | null;
  ESPBuyingOD: string | null;
  SEKSelling: string | null;
  SEKBuyingTT: string | null;
  SEKBuyingOD: string | null;
  CHFSelling: string | null;
  CHFBuyingTT: string | null;
  CHFBuyingOD: string | null;
  THBSelling: string | null;
  THBBuyingTT: string | null;
  THBBuyingOD: string | null;
  USDSelling: string | null;
  USDBuyingTT: string | null;
  USDBuyingOD: string | null;
  EURSelling: string | null;
  EURBuyingTT: string | null;
  EURBuyingOD: string | null;
  WONSelling: string | null;
  WONBuyingTT: string | null;
  WONBuyingOD: string | null;
  NTDSelling: string | null;
  NTDBuyingTT: string | null;
  NTDBuyingOD: string | null;
  RMBSelling: string | null;
  RMBBuyingTT: string | null;
  RMBBuyingOD: string | null;
  IEPSelling: string | null;
  IEPBuyingTT: string | null;
  IEPBuyingOD: string | null;
  GBPSelling: string | null;
  GBPBuyingTT: string | null;
  GBPBuyingOD: string | null;
  USD1Selling: string | null;
  USD2Selling: string | null;
  USD3Selling: string | null;
  USD4Selling: string | null;
  USD5Selling: string | null;
  USD6Selling: string | null;
  USD1BuyingTT: string | null;
  USD2BuyingTT: string | null;
  USD3BuyingTT: string | null;
  USD4BuyingTT: string | null;
  USD5BuyingTT: string | null;
  USD6BuyingTT: string | null;
  GBP1Selling: string | null;
  GBP2Selling: string | null;
  GBP3Selling: string | null;
  GBP4Selling: string | null;
  GBP5Selling: string | null;
  GBP6Selling: string | null;
  GBP1BuyingTT: string | null;
  GBP2BuyingTT: string | null;
  GBP3BuyingTT: string | null;
  GBP4BuyingTT: string | null;
  GBP5BuyingTT: string | null;
  GBP6BuyingTT: string | null;
  status: string;
  sent_usrid: string | null;
  sent_date: string | null;
  last_updateusrid: string | null;
  last_updateDate: string | null;
  rev_cnt: string;
  CNYSelling: string | null;
  CNYBuyingTT: string | null;
  CNYBuyingOD: string | null;
  CNHSelling: string | null;
  CNHBuyingTT: string | null;
  CNHBuyingOD: string | null;
  created_at: string;
  updated_at: string;
}
